plugins:
  - jest
env:
  jest/globals: true
  node: true
extends: 
- 'airbnb-base'
- 'plugin:jest/recommended'
overrides: []
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  jest/no-disabled-tests: warn
  jest/prefer-to-have-length: warn
  no-console: 0
  import/extensions:
    - error
    - ignorePackages
    - js: always
